package com.project.content.contentmanagementservice.model;

import lombok.*;

import java.util.Map;
import java.time.Instant;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Template {
    private String id; // Autogenerated
    private String ownerId;
    private String templateName;
    private Long createdAt;
    private Map<String, Object> templateData;
}
